language: python

cache:
  - pip

python:
 - "3.5"
 - "3.6"
 - "3.7-dev"

addons:
 postgresql: "9.6"

env:
 - DJANGO_VERSION=1.11.*
 - DJANGO_VERSION=2.0.*
 - DJANGO_VERSION=2.1.*

install:
 - pip install -r requirements.txt --no-binary opencivicdata
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
 - cp example/project/settings_local.py.template example/settings_local.py
 - psql -c 'CREATE DATABASE calaccess_processed;' -U postgres

script:
 - make flake8
 - coverage run example/manage.py test calaccess_processed

after_success:
 - coveralls
